server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: api-gateway

  jackson:
    visibility:
      field: any

  cloud:
    gateway:
      routes:
        # -----------------------------
        # NORMAL GATEWAY ROUTES
        # -----------------------------

        # User Authentication (Public)
        - id: user-public
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # User Protected Endpoints
        - id: user-protected
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter

        # Job Protected Endpoints
        - id: job-service-protected
          uri: lb://jobservice
          predicates:
            - Path=/api/jobs/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter

        # Job Public Endpoints
        - id: job-service-public
          uri: lb://jobservice
          predicates:
            - Path=/api/public/**
          filters:
            - StripPrefix=1

        # Job Applications Protected
        - id: application-protected
          uri: lb://application-service
          predicates:
            - Path=/api/job-applications/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter

        # Job Applications Public
        - id: application-public
          uri: lb://application-service
          predicates:
            - Path=/api/all/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true

  threads:
    virtual:
      enabled: true


# -----------------------------
# EUREKA CONFIG
# -----------------------------
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true


# -----------------------------
# LOGGING FORMAT
# -----------------------------
logging:
  pattern:
    console: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"


# -----------------------------
# ACTUATOR, HEALTH, ZIPKIN
# -----------------------------
management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans






# -----------------------------
# JWT SECRET
# -----------------------------
app:
  jwt-secret: ${JWT_SECRET_KEY}
