server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-public
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-protected
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter

        - id: job-service-protected
          uri: lb://jobservice
          predicates:
            - Path=/api/jobs/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter


        - id: job-service-public
          uri: lb://jobservice
          predicates:
            - Path=/api/public/**
          filters:
            - StripPrefix=1

        - id: job-application-protected
          uri: lb://application-service
          predicates:
              - Path=/api/job-applications/**
          filters:
              - StripPrefix=1
              - name: AuthenticationFilter


        - id: job-application-public
          uri: lb://application-service
          predicates:
              - Path=/api/all/**
          filters:
              - StripPrefix=1



      discovery:
        locator:
          enabled: true


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true

app:
  jwt-secret: ${JWT_SECRET_KEY}


logging:
  pattern:
    console: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"

# ----------------------------------------------------------------
# MANAGEMENT, ACTUATOR, & TRACING CONFIGURATION
# ----------------------------------------------------------------
management:
  tracing:
    enabled: true
    zipkin:
      base-url: "http://zipkin:9411/api/v2/spans"
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,zipkin"