server:
  port: ${USER_SERVICE_PORT}

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

app:
  jwt-secret: ${JWT_SECRET_KEY}


logging:
  pattern:
    console: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"

# ----------------------------------------------------------------
# MANAGEMENT, ACTUATOR, & TRACING CONFIGURATION
# ----------------------------------------------------------------
management:
  tracing:
    enabled: true
    zipkin:
      base-url: "http://zipkin:9411/api/v2/spans"
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,zipkin"