server:
  port: ${APPLICATION_SERVICE_PORT:8083}

spring :
  application :
    name : application-service
  datasource :
    url: ${APPLICATION_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${KAFKA_APPLICATION_SERVICE_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true

app:
  kafka:
    topics:
      job-application: ${KAFKA_TOPIC_JOB_APPLICATION}

logging:
  pattern:
    console: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"

# ----------------------------------------------------------------
# MANAGEMENT, ACTUATOR, & TRACING CONFIGURATION
# ----------------------------------------------------------------
management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      userServiceBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50  # Open circuit if 50% of calls fail
        minimumNumberOfCalls: 5   # Wait for 5 calls before calculating failure rate
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s # Wait 5s before trying again
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      jobServiceBreaker: # <--- Add this
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        slidingWindowSize: 10
        # Important: Ignore 404s so they don't count as "failures" and open the circuit
        ignoreExceptions:
          - feign.FeignException.NotFound